// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1uuYc8m5IB6COwtwaKbGDWcsGBtXtD0',
    appId: '1:571887738572:web:a2932940240dbf23426c69',
    messagingSenderId: '571887738572',
    projectId: 'chattyapp-me',
    authDomain: 'chattyapp-me.firebaseapp.com',
    storageBucket: 'chattyapp-me.appspot.com',
    measurementId: 'G-NEXYNGR1WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7_JnA18FXQFR09QuSi0QwGgXcCZvunw',
    appId: '1:571887738572:android:64de2b5f14ade607426c69',
    messagingSenderId: '571887738572',
    projectId: 'chattyapp-me',
    storageBucket: 'chattyapp-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd4TlRpGg5EOd9ouiOTBma1N9bBN5Hpcs',
    appId: '1:571887738572:ios:3ffe360157679c2e426c69',
    messagingSenderId: '571887738572',
    projectId: 'chattyapp-me',
    storageBucket: 'chattyapp-me.appspot.com',
    iosBundleId: 'com.example.chatychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd4TlRpGg5EOd9ouiOTBma1N9bBN5Hpcs',
    appId: '1:571887738572:ios:47e60d5f91ecf940426c69',
    messagingSenderId: '571887738572',
    projectId: 'chattyapp-me',
    storageBucket: 'chattyapp-me.appspot.com',
    iosBundleId: 'com.example.chatychat.RunnerTests',
  );
}
